[atlas]
    numRobots                = [10]
    floorplan                = ["small_empty.txt"]         # filename in atlas/resources/maps
    initialPosition          = [[1,1]]                     # (0,0) is top-left
    relayAlgorithm           = ["Recovery"]                # options: Recovery, Naive, SelfHealing
    lowerPdrThreshold        = [0.7]                       # (for Recovery) trigger relay placement if below
    upperPdrThreshold        = [0.8]                       # (for Recovery) to determine relay position
    communicationModel       = ["PisterHack"]              # options: LineOfSight, Friis, UnitDisk, PisterHack
    numberOfRuns             = 1                           # number of simulations runs with same simSetting
