[atlas]
    ui = true

    [atlas.experiment]
        runs = 1
        description = "Running a default config experiment"
        [atlas.experiment.logging]
            name = "default_log" # semantic prefix to date-time-hash format

    [atlas.wireless]
        model = "Base"
        [atlas.wireless.propagation]
            model = ["Radius", "Friis", "Pister"]

    [atlas.orchestrator]
        [atlas.orchestrator.navigation]
            models = ["Atlas"]
            [atlas.orchestrator.navigation.relay]
                algorithms = ["recovery", "selfHealing", "naive"]
            [atlas.orchestrator.navigation.path_planning]
                algorithms = ["A*"] # ["Djikstras", "A*", "D*", "RRT"]
            [atlas.orchestrator.navigation.target_selector]
                algorithms = ["frontier"]

    [atlas.world]
        floorplans = ["scattered_obstacles.txt"]
        [atlas.world.robots]
            counts = [5, 10, 20]
            initial_positions = [[1, 1]]