[atlas]

    # general configurations

    ui          = true                                       # activate simulation GUI
    configId    = "default"                                  # configuration identifier
    description = "Running a default config experiment"
    name        = "Atlas_data"                               # semantic prefix to date-time-hash format

    # simSetting configurations

    numberOfRuns           = 1                               # number of simulations runs with same simSetting
    floorplanBlueprints    = ["small_empty.txt"]             # blueprints of areas being explored by robots (environment model)
    communicationProtocols = ["ConcurrentTransmission"]      # wireless communication protocol
    communicationModels    = ["Pister"]                      # wireless propagation model
    pathPlanningAlgorithms = ["A*"]                          # path planning algorithms for robot navigation
    navigationAlgorithms   = ["Atlas"]                       # navigation and mapping algorithms
    relayAlgorithms        = ["Recovery"]                    # relay placement algorithms
    lowerPdrThresholds     = [0.7]                           # pdr that triggers relay placement in recovery alg
    upperPdrThresholds     = [0.8]                           # pdr that determines relay placement position  in recovery alg
    swarmSizes             = [10]                            # number of robots in swarm
    initialPositions       = [[1,1]]                         # initial positions for robots
